### ISSUE TITLE
Error in translation, i18nextXHRBackend

### ISSUE THREAD

**Issue by anupzone** [ivmartel/dwv-angular#220] opened 2021-02-17 12:51 UTC
i18nextXHRBackend deprecated and giving error in initializing dwv.i18nInitialise()

<img width="866" alt="Screenshot 2021-02-17 at 6 21 58 PM" src="https://user-images.githubusercontent.com/4955675/108206950-185b7700-714d-11eb-86cf-a695be8d2e37.png">

**Comment by ppacher** [comment] 2021-09-10 11:20
Hi, I'm facing the same issue here and was forced to downgrade dwv from 0.29 back to 0.27 to get it working again. AFAIK the issue is actually in ivmartel/dwv and not in the angular specific repo. Unless there's a different workaround available I'll  try to get it to work using i18nextHTTPBackend the next days.

**Comment by ivmartel** [comment] 2021-12-09 14:32
See [dwv/issues/1049](https://github.com/ivmartel/dwv/issues/1049) for the update of the i18nextHTTPBackend package.

**Comment by ivmartel** [comment] 2021-12-10 17:53
And #1057 for the module load.

**Comment by ivmartel** [comment] 2021-12-13 12:29
It looks like the update to dwv v0.30.4 fixed this issue!

**Comment by ivmartel** [comment] 2021-12-14 08:23
Closing for now, feel free to comment if this is still a problem.

**Closed by ivmartel** 2021-12-14 08:23 UTC
Labels: question
