### ISSUE TITLE
Failed to execute 'drawImage' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by osama11110** [ivmartel/dwv-angular#399] opened 2022-03-02 14:04 UTC
When I drop dicom file in the box it gives the following error  in the console and doesn't show the image
" DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0."

**Comment by ivmartel** [comment] 2022-03-03 08:15
This error usually comes from a badly initialised layer div, for the angular component this would be the `layerGroup0` div. Are you running from modified source code?

**Comment by osama11110** [comment] 2022-03-04 09:10
No, i've git clone this repository

**Comment by ivmartel** [comment] 2022-03-04 09:29
ok... I can't reproduce with Chrome nor Firefox, which browser are you using? It should not be data related, but just in case, does it give the same error with different data? Do you have the same error from the demo page (https://ivmartel.github.io/dwv-angular/demo/stable/index.html)?

**Comment by osama11110** [comment] 2022-03-04 11:12
No, it's working fine on demo

**Comment by osama11110** [comment] 2022-03-04 11:24
i am using opera gx but i've also tested on mozilla still the same error

**Comment by ivmartel** [comment] 2023-07-05 10:29
I hope you solved your error. Closing for now, feel free to comment if you need.

**Closed by ivmartel** 2023-07-05 10:29 UTC
Labels: question
